### ISSUE TITLE
Feature Request - Addition of Benchmarking for TRT-LLM

### ISSUE THREAD

**Issue by aswkumar99** [openhackathons-org/End-to-End-LLM#17]
The current TRT-LLM Materials discusses the Hands-on aspects of getting from a Model to Deployment in a Triton server. 

Given that TRT-LLM focuses on Performance, we could have a section that discusses the performance aspects of TRT-LLM and the various optimisations that are available to the end user.

**Comment by programmah** [comment]
The feature request has been added in #26
