### ISSUE TITLE
Issue: Deployment guide is outdated or incorrect

### ISSUE THREAD

**Issue by pablodonisebri** [openhackathons-org/End-to-End-LLM#20]
Deployment guide is stating the following:

_When you are inside the container, launch jupyter lab: jupyter-lab --no-browser --allow-root --ip=0.0.0.0 --port=8888 --NotebookApp.token="" --notebook-dir=/workspace.

Open the browser at http://localhost:8888 and click on the Start_here.ipynb notebook_ 

But when building the container there is no actual  Start_here.ipynb (unless you go to archived/workspace, which indicates me that it is either deprecated or not well defined where i should look for the notebook).

**Comment by aswinkumar1999** [comment]
Hi @pablodonisebri ,

Yes, you are correct; the structure has recently been updated. 

Previously, it used to be a single `Start_Here.ipynb` is now split into three notebooks ( `Megatron-GPT.ipynb`, `NeMo-Guardrails.ipynb`, `TensorRT-LLM.ipynb` ) . You can start with Megatron, then go on to TensorRT and then finally Guardrails.

**Comment by pablodonisebri** [comment]
Thank you. Closing the issue
